# Generated by Django 2.0 on 2017-12-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mxdistrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CiudadDeMexico',
        ),
    ]
