# Generated by Django 2.0 on 2017-12-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20171206_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
